on: [push]
jobs:
  validate-targets:
    name: Validate smokeping targets
    runs-on: ubuntu-24.04
    steps:
      - name: checkout self/this
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: self
      - name: Install jsonschema
        run: |
          sudo apt-get install -y python3-jsonschema
      - name: validate json
        run: |
          find targets -type f -print0 | xargs -0 -n1 jsonschema schema.json -i